import { atcb_init } from 'add-to-calendar-button'; // eslint-disable-line camelcase
import balanceText from 'balance-text';
import './src/lib/prism.min.js';
import './src/alerts.js';
import './src/announcements.js';
import './src/carousels.js';
import './src/clipboard.js';
import './src/callouts.js';
import './src/ts/code.ts';
import './src/collapse-nested.js';
import './src/collapse-responsive.js';
import './src/collapse-topnav.js';
import './src/collapse-y-height.js';
import './src/dropdown-hover.js';
import './src/internal-url.js';
import './src/lazyload.js';
import './src/loader.js';
import './src/markdown.js';
import './src/org.js';
import './src/pricing-calculator.js';
import './src/scrollspy.js';
import './src/show-hide.js';
import './src/shuffle.js';
import './src/splide.js';
import './src/sticky-top.js';
import './src/ts/tab-multiples.ts';
import './src/terminal.js';
import './src/toggle-fade-show.js';
import './src/theme-toggle.js';
atcb_init();
balanceText();
