import { atcb_init } from 'add-to-calendar-button'; // eslint-disable-line camelcase
import balanceText from 'balance-text';
import './src/lib/prism.min.js';
import './src/chocolatey-alerts.js';
import './src/chocolatey-announcements.js';
import './src/chocolatey-carousels.js';
import './src/chocolatey-clipboard.js';
import './src/chocolatey-callouts.js';
import './src/ts/chocolatey-code.ts';
import './src/chocolatey-collapse-nested.js';
import './src/chocolatey-collapse-responsive.js';
import './src/chocolatey-collapse-topnav.js';
import './src/chocolatey-collapse-y-height.js';
import './src/chocolatey-dropdown-hover.js';
import './src/chocolatey-internal-url.js';
import './src/chocolatey-lazyload.js';
import './src/chocolatey-loader.js';
import './src/chocolatey-markdown.js';
import './src/chocolatey-org.js';
import './src/chocolatey-pricing-calculator.js';
import './src/chocolatey-scrollspy.js';
import './src/chocolatey-show-hide.js';
import './src/chocolatey-shuffle.js';
import './src/chocolatey-splide.js';
import './src/chocolatey-sticky-top.js';
import './src/ts/chocolatey-tab-multiples.ts';
import './src/chocolatey-terminal.js';
import './src/chocolatey-theme-toggle.js';
import './src/chocolatey-toggle-fade-show.js';
atcb_init();
balanceText();
