import { Alert, Button, Carousel, Collapse } from 'bootstrap';
import '../lib/prism.min.js';
import '../chocolatey-alerts.js';
import '../chocolatey-anchors.js';
import '../chocolatey-callouts.js';
import '../chocolatey-code.js';
import '../chocolatey-collapse-nested.js';
import '../chocolatey-markdown.js';
import '../chocolatey-placeholders.js';
import '../chocolatey-sticky-table.js';
import '../chocolatey-substrings.js';
import '../chocolatey-tables.js';
import '../chocolatey-theme-toggle.js';
