- name: "Accessibility"
  color: "5319E7"
  description: "Represents issues that are related to accessibility in UI such as WCAG, etc."
- name: "BoxstarterWebsite"
  color: "D4C5F9"
- name: "ChocolateyBlog"
  color: "D4C5F9"
- name: "ChocolateyCentralManagement"
  color: "D4C5F9"
- name: "ChocolateyCreditsGenerator"
  color: "D4C5F9"
- name: "ChocolateyDesign"
  color: "D4C5F9"
- name: "ChocolateyDocs"
  color: "D4C5F9"
- name: "ChocolateyFest"
  color: "D4C5F9"
- name: "ChocolateyHome"
  color: "D4C5F9"
- name: "ChocolateyLicensing"
  color: "D4C5F9"
- name: "ChocolateyWebsite"
  color: "D4C5F9"
- name: "ChocolateyZendeskCopenhagen"
  color: "D4C5F9"
- name: "PackageAssets"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/assets package."
- name: "PackageAstro"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/astro package."
- name: "PackageBlog"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/blog package."
- name: "PackageBoxstarter"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/boxstarter package."
- name: "PackageBuildTools"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/build-tools package."
- name: "PackageCCM"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/ccm package."
- name: "PackageCCR"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/ccr package."
- name: "PackageCore"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/core package."
- name: "PackageCredits"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/credits package."
- name: "PackageDesign"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/design package."
- name: "PackageDocs"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/docs package."
- name: "PackageFeedTools"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/feed-tools package."
- name: "PackageFest"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/fest package."
- name: "PackageLicensing"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/licensing package."
- name: "PackageOrg"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/org package."
- name: "PackagePlaywright"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/playwright package."
- name: "PackageRoot"
  color: "D345E6"
  description: "Issues relating to the root source code."
- name: "PackageZendesk"
  color: "D345E6"
  description: "Issues relating to the @chocolatey-software/zendesk package."