checksumBehavior: update

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  chocolatey-software:
    npmRegistryServer: "https://registry.npmjs.org"
