approvedGitRepositories:
  - "**"

checksumBehavior: update

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  chocolatey-software:
    npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.15.0.cjs
