name: ESLint
on: [pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
      - run: yarn
      - run: yarn eslint
