name: Publish Dry Run
on: [pull_request]
jobs:
  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
      - run: yarn
      - run: yarn publish-dry-run
